# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('temp', models.CharField(default='None', max_length=200)),
                ('temp_kf', models.CharField(default='None', max_length=200)),
                ('temp_max', models.CharField(default='None', max_length=200)),
                ('temp_min', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
